AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InventoryAccountId:
    Type: String
    Description: The AWS Account ID where the Steampipe inventory process will be deployed.
Resources:
  RoleSteampipeInventory:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${InventoryAccountId}:root'
          Action: sts:AssumeRole
      Description: Used for daily inventory snapshots
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: SteampipeInventory
